# Generated by Django 5.1.6 on 2025-04-09 18:13

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Servico',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nome', models.CharField(max_length=500)),
                ('endereco', models.CharField(max_length=250)),
                ('anaminese', models.BooleanField()),
                ('descricao', models.CharField(max_length=200)),
                ('telefone', models.CharField(blank=True, max_length=15)),
            ],
        ),
    ]
