# Generated by Django 5.1.6 on 2025-04-09 21:12

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='servico',
            name='anaminese',
        ),
        migrations.AddField(
            model_name='servico',
            name='anamnese_obrigatoria',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='servico',
            name='duracao_minutos',
            field=models.PositiveIntegerField(default=60),
        ),
        migrations.CreateModel(
            name='Anamnese',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('servico', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to='servico.servico')),
            ],
        ),
        migrations.CreateModel(
            name='Pergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('texto', models.CharField(max_length=300)),
                ('formulario', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, to='servico.anamnese')),
            ],
        ),
    ]
