# Generated by Django 5.1.6 on 2025-04-10 00:57

import django.db.models.deletion
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('servico', '0002_remove_servico_anaminese_and_more'),
    ]

    operations = [
        migrations.AlterModelOptions(
            name='pergunta',
            options={'ordering': ['ordem'], 'verbose_name': 'Pergunta', 'verbose_name_plural': 'Perguntas'},
        ),
        migrations.RemoveField(
            model_name='pergunta',
            name='formulario',
        ),
        migrations.AddField(
            model_name='anamnese',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='descricao',
            field=models.TextField(blank=True),
        ),
        migrations.AddField(
            model_name='anamnese',
            name='titulo',
            field=models.CharField(default='Formulário de Anamnese', max_length=100),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='anamnese',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.CASCADE, related_name='perguntas', to='servico.anamnese'),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ativo',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='obrigatorio',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='ordem',
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AddField(
            model_name='pergunta',
            name='tipo',
            field=models.CharField(choices=[('texto', 'Resposta Textual'), ('textarea', 'Texto Longo'), ('numero', 'Número'), ('email', 'E-mail'), ('telefone', 'Telefone'), ('data', 'Data'), ('select', 'Seleção Única'), ('multiselect', 'Seleção Múltipla'), ('checkbox', 'Checkbox')], default='texto', max_length=20),
        ),
        migrations.AlterField(
            model_name='anamnese',
            name='servico',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='anamneses', to='servico.servico'),
        ),
        migrations.AlterField(
            model_name='pergunta',
            name='texto',
            field=models.CharField(max_length=500),
        ),
        migrations.CreateModel(
            name='OpcaoPergunta',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('valor', models.CharField(max_length=100)),
                ('texto', models.CharField(max_length=200)),
                ('pergunta', models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='opcoes', to='servico.pergunta')),
            ],
            options={
                'verbose_name': 'Opção de Pergunta',
                'verbose_name_plural': 'Opções de Pergunta',
            },
        ),
    ]
